name: utilbil
favicon: null
layout_spectrum: 0.7450453012716025
typography_spectrum: 0.29025820759125054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9950710171833634
  lightness: 0.7420004769228399
  saturation: 0.6449274653568864
  rhythmicContrast: 0.6970083324704319
purpose: []
